[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/blog/*.md"
  to = "/blog/:splat"
  status = 200
  # Ensure direct serving of markdown files

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
