[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
